# Makefile
# Řešení IJC-DU2, příklad 1) a 2), 8.4. 2023
# Autor: Jakub Antonín Štigler, FIT
# Přeloženo: cc - clang 15.0.7
#   Funguje s gcc 12.2.1
# Usage:
#   make # builds tail, wordcount and wordcount-dynamic
#   make wordcount++ # builds wordcount++
#   make clean # deletes all files generated by makefile
#   make CFLAGS=-DSTATISTICS # adds statistics to the wordcount program

override CFLAGS:= -g -Wall -pedantic -std=c11 -Wextra -O2 -fPIC $(CFLAGS)
override LDFLAGS:= -g -O2 $(LDFLAGS)
HTAB:=htab_basic.o htab_clean.o htab_for_each.o htab_hash_function.o \
htab_lookup.o htab_statistics.o htab_primes.o

.PHONY: all clean

all: tail wordcount wordcount-dynamic

T:=$(shell $(CC) -MM *.c > dep.d)
-include dep.d

tail:

libhtab.a: $(HTAB)
	ar r $@ $^

libhtab.so: $(HTAB)
	$(CC) -shared -o $@ $^

wordcount: io.o wordcount.o libhtab.a
	$(CC) $(LDFLAGS) -o $@ $^

wordcount-dynamic: io.o wordcount.o libhtab.so
	$(CC) $(LDFLAGS) -o $@ $^

wordcount++:

clean:
	-rm *.o tail *.a wordcount *.so wordcount-dynamic wordcount++ dep.d \
	wordcount++.o
